2020-07-06 09:23:29,052 [none] django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-07-06 09:23:34,925 [none] django.request WARNING  Not Found: /manifest.json
2020-07-06 09:23:34,927 [none] django.request WARNING  Not Found: /favicon.ico
2020-07-06 09:28:01,359 [none] asyncio      DEBUG    Using proactor: IocpProactor
2020-07-06 09:28:01,439 [none] asyncio      DEBUG    Using proactor: IocpProactor
2020-07-15 12:28:06,212 [none] django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-07-15 12:28:12,547 [none] django.request ERROR    Internal Server Error: /index/
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python38\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python38\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "C:\Python38\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Python38\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Python38\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Python38\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
2020-07-15 12:34:13,410 [none] asyncio      DEBUG    Using proactor: IocpProactor
2020-07-15 12:34:13,523 [none] asyncio      DEBUG    Using proactor: IocpProactor
2020-07-15 12:37:06,114 [none] django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-07-15 12:37:08,457 [none] django.request WARNING  Not Found: /manifest.json
2020-07-15 12:37:16,834 [none] asyncio      DEBUG    Using proactor: IocpProactor
2020-07-15 12:37:16,925 [none] asyncio      DEBUG    Using proactor: IocpProactor
2020-07-15 17:55:35,540 [none] django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-07-15 17:55:38,297 [none] django.request ERROR    Internal Server Error: /index/
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python38\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python38\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "C:\Python38\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Python38\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Python38\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Python38\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
2020-07-15 17:55:39,191 [none] django.request WARNING  Not Found: /favicon.ico
2020-07-15 18:15:57,583 [none] django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-07-15 18:16:01,021 [none] django.request WARNING  Not Found: /favicon.ico
2020-07-15 18:16:03,177 [none] django.request ERROR    Internal Server Error: /index/
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python38\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python38\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "C:\Python38\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Python38\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Python38\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Python38\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
